#!/bin/bash
# Use current working directory
#$ -cwd
#
# Join stdout and stderr
#$ -j n
#$ -o /mnt/atgc-d1/bioinfoII/rnaseq/BioProject_2025/Practica/scripts/out_logs/DownloadData.out
#$ -e /mnt/atgc-d1/bioinfoII/rnaseq/BioProject_2025/Practica/scripts/out_logs/DownloadData.err
#
# Run job through bash shell
#$ -S /bin/bash
#
#You can edit the scriptsince this line
#
# Your job name
#$ -N DownloadData
#
# Memory
#$ -l vf=4G
#
# Send an email after the job has finished
#$ -m e
#$ -M ecossnav@gmail.com
#
# If modules are needed, source modules environment (Do not delete the next line):
. /etc/profile.d/modules.sh
#
# Add any modules you might require:
# Write your commands in the next line
cd /mnt/atgc-d1/bioinfoII/rnaseq/BioProject_2025/Practica/data/

wget -nc ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR271/085/SRR27190685/SRR27190685_2.fastq.gz
wget -nc ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR271/084/SRR27190684/SRR27190684_1.fastq.gz
wget -nc ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR271/008/SRR27190708/SRR27190708_1.fastq.gz
wget -nc ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR271/076/SRR27190676/SRR27190676_2.fastq.gz
wget -nc ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR271/010/SRR27190710/SRR27190710_1.fastq.gz
wget -nc ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR271/084/SRR27190684/SRR27190684_2.fastq.gz
wget -nc ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR271/000/SRR27190700/SRR27190700_1.fastq.gz
wget -nc ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR271/008/SRR27190708/SRR27190708_2.fastq.gz
wget -nc ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR271/010/SRR27190710/SRR27190710_2.fastq.gz
wget -nc ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR271/076/SRR27190676/SRR27190676_1.fastq.gz
wget -nc ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR271/085/SRR27190685/SRR27190685_1.fastq.gz
wget -nc ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR271/000/SRR27190700/SRR27190700_2.fastq.gz
